#!/usr/bin/env bash
echo ""
echo "    remove existing version of topmodelr..."
echo ""
R -q -e 'packrat::clean("topmodelr", force=T)'
echo ""
echo "    install topmodelr from github repository..."
echo ""
if [ -f .Rprofile ]; then
   mv .Rprofile .Rprofile2
fi
R -q -e 'source("packrat/init.R");devtools::install_github("herreio/topmodelr")'
if [ -f .Rprofile2 ]; then
   mv .Rprofile2 .Rprofile
fi
echo ""
echo "    all done..."
echo ""
